### ISSUE TITLE
Search non-functional?

### ISSUE THREAD

**Issue by xnaas** [b3yc0d3/rule34Py#1]
Example .py:

```py
from __future__ import absolute_import, division, print_function, unicode_literals
from rule34Py import rule34Py


r34 = rule34Py()
image = r34.search("slime")
print(image)
```

Result:

```
[{'id': None, 'score': None, 'rating': None, 'creator_id': None, 'created_at': None, 'source': (None,), 'has_notes': None, 'tags': None, 'img_sample_url': None, 'img_file_url': None, 'img_preview_url': None}]
```

Anything I'm missing?

**Comment by b3yc0d3** [comment]
You don't missed something, it's my fault. I forgot to write it in the Documentation.
I've updated all, and fixed it.
The tag Parameter for search must be a list.
example:
`r34Py.search(["slime"])`

_I apologize for my mistake_

**Comment by xnaas** [comment]
Aha, works perfectly. Thank you. :)
