### ISSUE TITLE
make random_post print more than 1 result.

### ISSUE THREAD

**Issue by rV4nxZ** [b3yc0d3/rule34Py#10]
tried to do a loop:
```python
results = []

for i in range(5):
    result = r34Py.random_post(["sexy"])
    results.append(result.image)

for url in results:
    print(url)
```
 
but that is slow. Can anyone help?

**Comment by b3yc0d3** [comment]
The reason why `random_post` with specific tags takes so long (~2 sec) is,
rule34s official api doesn't have an endpoint for random posts with tags.
[Here](https://github.com/b3yc0d3/rule34Py/blob/master/rule34Py/rule34.py#L301) i've done a "work a round" which basically makes a search request with tags,
then just picks a random one out of the result.
*The function `random_post` is faster when there are no tags given.*

You could run that piece of code in a [async](https://pypi.org/project/asyncio/) function.

**Comment by rV4nxZ** [comment]
AttributeError: 'list' object has no attribute 'get_post', code:
```python
from rule34Py import rule34Py
import asyncio

r34Py = rule34Py

async def main():
    results = []
    for i in range(5):
        result = r34Py.random_post(["sexy"])
        await results.append(result.image)

    for url in results:
        print(url)

asyncio.run(main())
```
i tried

**Comment by rV4nxZ** [comment]
now self.get_post is not working

**Comment by b3yc0d3** [comment]
it's weird, for me that example works, without errors:
```py
from rule34Py import rule34Py
import asyncio

r34Py = rule34Py()

async def main():
    results = []
    for i in range(5):
        result = r34Py.random_post(["sexy"]) # example
        results.append(result.image)

    for url in results:
        print(url)

asyncio.run(main())
```
i'll look deeper in to the problem as soon as i've time.

**Comment by rV4nxZ** [comment]
That works, but there is this problem of slowness.

**Comment by rV4nxZ** [comment]
And how i can print videos instead

**Comment by b3yc0d3** [comment]
> That works, but there is this problem of slowness.

To be honest, i personally don't know how i could make it faster when tags are used.
<br>

> And how i can print videos instead

You can use [`<Post>.video`](https://github.com/b3yc0d3/rule34Py/blob/master/DOC/post.md#video) to get the video URL.

**Comment by rV4nxZ** [comment]
i'll be good to add multiple tags
