### ISSUE TITLE
AttributeError: 'Post' object has no attribute 'file_type'

### ISSUE THREAD

**Issue by MopigamesYT** [b3yc0d3/rule34Py#12]
title says it
here's my code:
```
                if post.file_type == "video":
                    links += f"[{i + 1}] This is a video! Click on the Source button to see it on r34!\n"
```

**Comment by b3yc0d3** [comment]
the attribute of the `Post` class which holds this value is called `content_type`. Also there is `_file_type`, which both can be used (tho `_file_type` isn't meant to be used by users)

**Comment by MopigamesYT** [comment]
Thanks!
