### ISSUE TITLE
Random fonction broken

### ISSUE THREAD

**Issue by Krafting** [b3yc0d3/rule34Py#2]
hello there,
So I think I found a bug in the random function.
Imagine doing a search that result in only 2 posts, then, the posts starts at id=0 and not id=1.
When using the randint(), we need to start at 0 and finish at "self.search(tags, 0, 0)[0] - 1" the search return 2 posts, but the id are 0 and 1

Current code:
```
        if tags != None:
            rand_num = random.randint(1, self.search(tags, 0, 0)[0])
            return self.search(tags, rand_num, 1)[1]
```
"Fixed code:
```
        if tags != None:
            rand_num = random.randint(0, self.search(tags, 0, 0)[0]-1)
            return self.search(tags, rand_num, 1)[1]
```

In the current state, if we do a search with only 2 images, it break the script half the time, the other half, it return the image with id=1.

I'm bad at explaining stuff, I hope that I made it (approximately) clear.
You can try this search term (what I used) : "calmadman" https://rule34.xxx/index.php?page=post&s=list&tags=calmadman

**Comment by b3yc0d3** [comment]
thank you @Krafting for the info,
i hope i've fixed the bug

**Comment by Krafting** [comment]
Okey, so the bug is fixed, but I found that if you use the random() function with  a term that return nothing 
Example:
`
                            r34Py = rule34Py.rule34Py()

                            searchImage = r34Py.random(['sfdkjugohdsfgkjh'])
                            print(searchImage)
                           print("This print doesn't go through, it's stuck")
`

Then, the script is stuck, the random function doesn't return an error, it seems to get stuck in some way. 

here is a workaround I do using the search function instead (if this helps) :
`r34Py = rule34Py.rule34Py()
                            try: 
                                rand_num = random.randint(0, r34Py.search(['sdfkjhsdfkjsdhfksjdhf'], 0, 100)[0]-1)
                                searchImage = r34Py.search(['sdfkjhsdfkjsdhfksjdhf'], rand_num, 1)[1]['img_file_url']
                                print(searchImage)
                            except Exception:
                                print("Not found")
                                continue`

**Comment by b3yc0d3** [comment]
i'll try to fix that in the next update
