### ISSUE TITLE
Search limit

### ISSUE THREAD

**Issue by RemNX** [b3yc0d3/rule34Py#7]
Hello, i want more than 1000 posts in the random_post command but even if i use the ignore_max_limit in the search command the command give me a maximum of 1000 posts

```
a=r3.search(["ass"], limit=2000,ignore_max_limit=True)
for i in a:
    print(i.id)

print(len(a))
```
`len(a)=1000`

**Comment by b3yc0d3** [comment]
Sorry for the late answer
The max limit of 1000 is set by the Rest API of rule34 (or more like how they set danbooru over there),
as the official Rest API [Documentation sayes](https://rule34.xxx/index.php?page=help&topic=dapi)
